package InterfaceUSER;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author quang
 */
public class HomeQL extends javax.swing.JFrame {

    /**
     * Creates new form MenuQL
     */
    public HomeQL() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnqlGoiBoi = new javax.swing.JButton();
        btnqlDoanhThu = new javax.swing.JButton();
        btnqlDichVu = new javax.swing.JButton();
        btnqlTaiKhoan = new javax.swing.JButton();
        btnqlVeSinh = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý hồ bơi(Quản lý)");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Phần mềm quản lý hồ bơi");

        btnqlGoiBoi.setBackground(new java.awt.Color(255, 255, 255));
        btnqlGoiBoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnqlGoiBoi.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Goiboi2.jpg")); // NOI18N
        btnqlGoiBoi.setText("Quản lý gói bơi");
        btnqlGoiBoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlGoiBoiActionPerformed(evt);
            }
        });

        btnqlDoanhThu.setBackground(new java.awt.Color(153, 255, 153));
        btnqlDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnqlDoanhThu.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Payroll.png")); // NOI18N
        btnqlDoanhThu.setText("Quản lý doanh thu");
        btnqlDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlDoanhThuActionPerformed(evt);
            }
        });

        btnqlDichVu.setBackground(new java.awt.Color(255, 153, 0));
        btnqlDichVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnqlDichVu.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Cart.png")); // NOI18N
        btnqlDichVu.setText("Quản lý dịch vụ");
        btnqlDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlDichVuActionPerformed(evt);
            }
        });

        btnqlTaiKhoan.setBackground(new java.awt.Color(0, 204, 255));
        btnqlTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnqlTaiKhoan.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Change PasssWord.png")); // NOI18N
        btnqlTaiKhoan.setText("Quản lý tài khoản");
        btnqlTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlTaiKhoanActionPerformed(evt);
            }
        });

        btnqlVeSinh.setBackground(new java.awt.Color(255, 255, 255));
        btnqlVeSinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnqlVeSinh.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\VeSinh.jpg")); // NOI18N
        btnqlVeSinh.setText("Quản lý vệ sinh");
        btnqlVeSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlVeSinhActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(204, 204, 255));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\LogOut.png")); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnqlDichVu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnqlTaiKhoan, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnqlVeSinh, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnqlDoanhThu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnqlGoiBoi, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(81, 81, 81))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDangXuat, btnqlDichVu, btnqlDoanhThu, btnqlGoiBoi, btnqlTaiKhoan, btnqlVeSinh});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnqlTaiKhoan)
                    .addComponent(btnqlGoiBoi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnqlDichVu)
                    .addComponent(btnqlDoanhThu))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangXuat)
                    .addComponent(btnqlVeSinh))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnqlDichVu, btnqlDoanhThu, btnqlGoiBoi, btnqlTaiKhoan});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnqlDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlDoanhThuActionPerformed
        // TODO add your handling code here:
        QuanLyDoanhThu qldt = new QuanLyDoanhThu();
        qldt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnqlDoanhThuActionPerformed

    private void btnqlTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlTaiKhoanActionPerformed
        // TODO add your handling code here:
        QuanLyTaiKhoan qltk = new QuanLyTaiKhoan();
        qltk.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnqlTaiKhoanActionPerformed

    private void btnqlGoiBoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlGoiBoiActionPerformed
        // TODO add your handling code here:
        QuanLyGoiBoi qlgb = new QuanLyGoiBoi();
        qlgb.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnqlGoiBoiActionPerformed

    private void btnqlDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlDichVuActionPerformed
        // TODO add your handling code here:
        QuanLyMenuDichVu qldv = new QuanLyMenuDichVu();
        qldv.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnqlDichVuActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        LogIn li = new LogIn();
        li.setVisible(true); 
        this.setVisible(false);

    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnqlVeSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlVeSinhActionPerformed
        // TODO add your handling code here:
        QuanLyGoiVeSinh qlvs = new QuanLyGoiVeSinh();
        qlvs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnqlVeSinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnqlDichVu;
    private javax.swing.JButton btnqlDoanhThu;
    private javax.swing.JButton btnqlGoiBoi;
    private javax.swing.JButton btnqlTaiKhoan;
    private javax.swing.JButton btnqlVeSinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
