package InterfaceUSER;

import Connect.ketNoi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quang
 */
public class QuanLyMenuDichVu extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyTaiKhoan
     */
    ketNoi k = new ketNoi();
    private int index;
    DefaultTableModel model = new DefaultTableModel();

    public QuanLyMenuDichVu() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản lý tài khoản");
        k.connect();
        loadDataToComboBox();
        loadDataToTable();
        showDetail(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDV = new javax.swing.JTable();
        txtMaVp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        txtVP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboDV = new javax.swing.JComboBox<>();
        lblTenLDV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\BackMini.png")); // NOI18N
        btnBack.setText("Hệ thống");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Quản lý các dịch vụ");

        tblDV.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã vật phẩm", "Vật phẩm", "Giá", "Số lượng"
            }
        ));
        tblDV.setGridColor(new java.awt.Color(153, 153, 153));
        tblDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDV);

        txtMaVp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã vật phẩm :");

        tbnNew.setBackground(new java.awt.Color(255, 255, 255));
        tbnNew.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        tbnNew.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Refresh-icon.png")); // NOI18N
        tbnNew.setText("Tạo mới");
        tbnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnNewActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Delete.png")); // NOI18N
        btnDelete.setText("Xoá");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(204, 255, 204));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\ChangePass.png")); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(204, 204, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Add.png")); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Số lượng :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Giá :");

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtVP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Vật phẩm :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã loại DV :");

        cboDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDVActionPerformed(evt);
            }
        });

        lblTenLDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenLDV.setForeground(new java.awt.Color(0, 51, 255));
        lblTenLDV.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                            .addComponent(txtVP, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblTenLDV)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cboDV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtMaVp, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))))))
                                .addContainerGap(195, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tbnNew)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAdd)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete)))
                                .addGap(0, 40, Short.MAX_VALUE))))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnDelete, btnUpdate, tbnNew});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(3, 3, 3)
                .addComponent(lblTenLDV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaVp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbnNew)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnDelete, btnUpdate, tbnNew});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        try {
            HomeQL ql = new HomeQL();
            ql.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Lỗi ql");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void tbnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnNewActionPerformed
        // TODO add your handling code here:
        try {
            clearForm();
        } catch (Exception e) {
            System.out.println("lỗi clearForm");
        }
    }//GEN-LAST:event_tbnNewActionPerformed

    private void cboDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDVActionPerformed
        // TODO add your handling code here:
        loadDataToTable();
    }//GEN-LAST:event_cboDVActionPerformed

    private void tblDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDVMouseClicked
        // TODO add your handling code here:
        try {
            index = tblDV.getSelectedRow();
            showDetail(index);
        } catch (Exception e) {
            System.out.println("Lỗi click");
        }
    }//GEN-LAST:event_tblDVMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            if (!checkNull()) {
                return;
            }
            try {
                Integer.parseInt(txtGia.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Giá phải là số");
                return;
            }
            try {
                Integer.parseInt(txtSoLuong.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số");
                return;
            }
            String sql = "Update dichvu set tenvp = ?, giavp = ?, soluongvp = ? where mavp = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, txtVP.getText());
            st.setString(2, txtGia.getText());
            st.setString(3, txtSoLuong.getText());
            st.setString(4, txtMaVp.getText());
            if (tblDV.getValueAt(index, 0).toString().equalsIgnoreCase(txtMaVp.getText())) {
                st.executeUpdate();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Mã vật phẩm phải giống trong bảng");
            }
            loadDataToTable();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá không ?", "Cảnh báo xoá", JOptionPane.YES_NO_OPTION);
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            } else {
            }
            String sql = "delete from dichvu where mavp = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, txtMaVp.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Bạn đã xoá thành công : " + txtVP.getText());
            loadDataToTable();
            if (tblDV.getRowCount() > 0) {
                showDetail(0);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            if (!checkNull()) {
                return;
            }
            if (!checkDup()) {
                return;
            }
            try {
                Integer.parseInt(txtGia.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Giá phải là số");
                return;
            }
            try {
                Integer.parseInt(txtSoLuong.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số");
                return;
            }
            String sql = "insert into DICHVU values(?,?,?,?,?,?)";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, txtMaVp.getText());
            st.setString(2, cboDV.getSelectedItem().toString());
            st.setString(3, txtVP.getText());
            st.setString(4, txtGia.getText());
            st.setString(5, txtSoLuong.getText());
            st.setString(6, "");
            st.executeUpdate();
            loadDataToTable();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMenuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMenuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMenuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMenuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMenuDichVu().setVisible(true);
            }
        });
    }

    private void loadDataToComboBox() {
        try {
            Statement st = k.cn.createStatement();
            String sql = "select * from loaidichvu";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                cboDV.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println("Không thể tảu dữ liệu lên comboBox");
        }
    }

    private void loadDataToTable() {
        try {
            model = (DefaultTableModel) tblDV.getModel();
            model.setRowCount(0);
            String sql = "select mavp, tenvp, giavp, soluongvp, tenldv from dichvu n inner join loaidichvu on loaidichvu.maldv = n.maldv where loaidichvu.MALDV = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, cboDV.getSelectedItem().toString());
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getString(4));
                lblTenLDV.setText(rs.getString(5));
                model.addRow(row);
            }
            tblDV.getModel();
            index = tblDV.getRowCount();
            if (index > 0) {
                index = 0;
                showDetail(index);
            } else {
                System.out.println("Bảng không có dữ liệu");
            }
        } catch (SQLException e) {
            System.out.println("Lỗi tải dữ liệu");
            clearForm();
        }
    }

    private void showDetail(int index) {
        txtMaVp.setText(tblDV.getValueAt(index, 0).toString());
        txtVP.setText(tblDV.getValueAt(index, 1).toString());
        txtGia.setText(tblDV.getValueAt(index, 2).toString());
        txtSoLuong.setText(tblDV.getValueAt(index, 3).toString());
        tblDV.setRowSelectionInterval(index, index);
    }

    private void clearForm() {
        showDetail(0);
        txtMaVp.setText("");
        txtVP.setText("");
        txtGia.setText("");
        txtSoLuong.setText("");

    }

    private boolean checkNull() {
        if (txtMaVp.getText().isEmpty()) {
            txtMaVp.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Mã vật phẩm trống");
            return false;
        } else if (txtVP.getText().isEmpty()) {
            txtVP.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Tên vật phẩm trống");
            return false;
        } else if (txtSoLuong.getText().isEmpty()) {
            txtSoLuong.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Số lượng vật phẩm trống");
            return false;
        } else if (txtGia.getText().isEmpty()) {
            txtGia.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Giá vật phẩm trống");
            return false;
        } else {
            return true;
        }
    }

    private boolean checkDup() {
        if (tblDV.getValueAt(index, 0).toString().equalsIgnoreCase(txtMaVp.getText())) {
            txtMaVp.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Mã VP đã tồn tại");
            return false;
        } else {
            return true;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTenLDV;
    private javax.swing.JTable tblDV;
    private javax.swing.JButton tbnNew;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaVp;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtVP;
    // End of variables declaration//GEN-END:variables
}
