package InterfaceUSER;

import Connect.ketNoi;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Formatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quang
 */
public class QuanLyVeSinh extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyTaiKhoan
     */
    private Date date = new java.util.Date();
    ketNoi k = new ketNoi();
    DefaultTableModel model = new DefaultTableModel();

    public QuanLyVeSinh() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản lý tài khoản");
        k.connect();
        dongHo();
        LoadUser();
        loadDataToComboBoxVeSinh();
        loadDataToTable();
        showMaVS();
        loadDataToLBL();
        lblTenNV.setText(lblUser.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        CboGoiVS = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblChiPhi = new javax.swing.JLabel();
        btnReFesh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblGoiVS = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblThoiGian = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        lblMaVSinh = new javax.swing.JLabel();
        lblChiPhi1 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        lblDate2 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblUser5 = new javax.swing.JLabel();
        lblThoiGian1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\BackMini.png")); // NOI18N
        btnBack.setText("Hệ thống");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Quản lý vệ sinh");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Chọn gói :");

        btnThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnThanhToan.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Goimoinini.jpg")); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        CboGoiVS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CboGoiVS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboGoiVSActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Chi phí :");

        lblChiPhi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblChiPhi.setForeground(new java.awt.Color(255, 0, 0));
        lblChiPhi.setText("---------");

        btnReFesh.setBackground(new java.awt.Color(255, 255, 255));
        btnReFesh.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnReFesh.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Refresh-icon.png")); // NOI18N
        btnReFesh.setText("Refesh");
        btnReFesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReFeshActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tên nhân viên :");

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNV.setText("quanglb");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Gói vệ sinh :");

        lblGoiVS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGoiVS.setText("---------");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Thời gian :");

        lblThoiGian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThoiGian.setText("---------");

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên gói", "Tên NV", "Giá gói", "Ngày thanh toán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl1);

        lblMaVSinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaVSinh.setText("---------");

        lblChiPhi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblChiPhi1.setForeground(new java.awt.Color(255, 0, 0));
        lblChiPhi1.setText("VNĐ");

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));

        lblDongHo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 0, 0));
        lblDongHo.setText("12 : 00 ");

        lblDate2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate2.setForeground(new java.awt.Color(255, 0, 0));
        lblDate2.setText("12/12/2020");

        lblUser.setBackground(new java.awt.Color(0, 204, 255));
        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 0, 204));
        lblUser.setText("Tên Gói Bơi");

        lblUser5.setBackground(new java.awt.Color(0, 204, 255));
        lblUser5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUser5.setForeground(new java.awt.Color(0, 0, 255));
        lblUser5.setText("Nhân viên :");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblDongHo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate2)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUser)
                .addGap(23, 23, 23))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDongHo)
                    .addComponent(lblDate2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(lblUser5))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblThoiGian1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThoiGian1.setText("Phút");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGoiVS)
                                    .addComponent(lblTenNV)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblThoiGian)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblThoiGian1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblChiPhi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChiPhi1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThanhToan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReFesh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaVSinh)
                    .addComponent(CboGoiVS, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CboGoiVS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMaVSinh)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblTenNV))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblGoiVS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblThoiGian)
                            .addComponent(lblThoiGian1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblChiPhi)
                            .addComponent(lblChiPhi1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReFesh)
                        .addGap(18, 18, 18)
                        .addComponent(btnThanhToan)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        try {
            ThanhToan();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnReFeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReFeshActionPerformed
        // TODO add your handling code here:
        try {
            loadDataToLBL();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnReFeshActionPerformed

    private void CboGoiVSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboGoiVSActionPerformed
        // TODO add your handling code here:
        showMaVS();

    }//GEN-LAST:event_CboGoiVSActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        try {
            HomeNV ql = new HomeNV();
            ql.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Lỗi ql");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyVeSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyVeSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyVeSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyVeSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyVeSinh().setVisible(true);
            }
        });
    }

    private void dongHo() {
        Thread t = new Thread() {
            String text;
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss aa");

            @Override
            public void run() {
                while (true) {
                    Date d = new Date(); //Tạo đối tượng Date để lấy giờ hệ thống
                    text = sdf.format(d);
                    lblDongHo.setText(text);
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }
        };
        t.start();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String dateFormat = formatter.format(date);
        lblDate2.setText(dateFormat);
    }

    private void loadDataToComboBoxVeSinh() {
        try {
            CboGoiVS.removeAllItems();
            Statement st = k.cn.createStatement();
            String sql = "select mavs from VESINH";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                CboGoiVS.addItem(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println("Không thể tải dữ liệu lên comboBox");
        }
    }

    private void loadDataToLBL() {
        try {
            String sql = "select thoigian, phivs from vesinh where mavs = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, CboGoiVS.getSelectedItem().toString());
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                lblThoiGian.setText(rs.getString(1));
                lblChiPhi.setText(rs.getString(2));
            }
            lblGoiVS.setText(lblMaVSinh.getText());
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void loadDataToTable() {
        try {
            model = (DefaultTableModel) tbl1.getModel();
            model.setRowCount(0);
            Statement st = k.cn.createStatement();
            ResultSet rs = st.executeQuery("select MAHOADONVS, TENVS, USERNAME, THANHTIEN, HOADONvs.THOIGIAN  from HOADONvs JOIN VESINH ON VESINH.MAVS  = HOADONVS.MAVS");
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getString(4));
                row.add(rs.getString(5));
                model.addRow(row);
            }
        } catch (SQLException e) {
            System.out.println("Lỗi tải dữ liệu" + e);
        }
    }

    private void showMaVS() {
        try {
            String sql = "select tenvs from vesinh where mavs = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, CboGoiVS.getSelectedItem().toString());
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                lblMaVSinh.setText(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void LoadUser() {
        try {
            String sql = "select * from tkol";
            Statement st = k.cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                lblUser.setText(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void ThanhToan() {
        try {
            int ngay, thang, nam;
            String day = lblDate2.getText();
            ngay = Integer.parseInt(day.substring(0, 2));
            thang = Integer.parseInt(day.substring(3, 5));
            nam = Integer.parseInt(day.substring(6, 10));
            String datee = thang + "-" + ngay + "-" + nam;
            //Thêm vào hoá đơn vệ sinh
            String sql2 = "insert into HOADONVS (mavs, thanhtien,THOIGIAN,maloaidoanhthu,username)  values(?,?,?,?,?)";
            PreparedStatement st2 = k.cn.prepareStatement(sql2);
            st2.setString(1, CboGoiVS.getSelectedItem().toString());
            st2.setString(2, lblChiPhi.getText());
            st2.setString(3, datee);
            st2.setString(4, "ChiPhiVeSinh");
            st2.setString(5, lblUser.getText());
            st2.executeUpdate();
            loadDataToTable();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyVeSinh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboGoiVS;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReFesh;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChiPhi;
    private javax.swing.JLabel lblChiPhi1;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblGoiVS;
    private javax.swing.JLabel lblMaVSinh;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblThoiGian1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUser5;
    private javax.swing.JTable tbl1;
    // End of variables declaration//GEN-END:variables
}
