package InterfaceUSER;

import Connect.ketNoi;
import java.awt.HeadlessException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quang
 */
public class QuanLyDichVu extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyTaiKhoan
     */
    ketNoi k = new ketNoi();
    private int index;
    DefaultTableModel model = new DefaultTableModel();

    public QuanLyDichVu() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản lý tài khoản");
        k.connect();
        dongHo();
        LoadUser();
        loadDataToComboBox(); //
        loadDataToComboBox2(); //
        LoadDataToTableBan();
        LoadDataToTableThue(); //
        LoadDataToTableBan2();
        LoadDataToTableThue2(); //
        LoadDataToTableDangThue(); //
        LoadDataToTableKH();
        showDetailBan(0);
        showDetailThue(0); //
        txtCCCD.setText("");
        txtHoTenThue.setText("");
        lblCCCDCF.setText("null");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnUong = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblTenVP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPhaiTraBan = new javax.swing.JLabel();
        btnThanhToanBan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblGiaVP = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAnUong2 = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        lblUser4 = new javax.swing.JLabel();
        lblMaHD = new javax.swing.JLabel();
        btnTaoMoi = new javax.swing.JButton();
        lblPhaiTraBan1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThue = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        lblTenVPThue = new javax.swing.JLabel();
        btnThue = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblGiaVPThue = new javax.swing.JLabel();
        btnThemThue = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtHoTenThue = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblPhaiTraThue = new javax.swing.JLabel();
        btnCFCCCD = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblThue2 = new javax.swing.JTable();
        btnXoaThue = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lblCCCDCF = new javax.swing.JLabel();
        cboCCCD1 = new javax.swing.JComboBox<>();
        btnTaoMoi_Thue = new javax.swing.JButton();
        lblUser5 = new javax.swing.JLabel();
        lblMaHD_thue = new javax.swing.JLabel();
        lblPhaiTraBan2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDCT = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnTra = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        lblTenKh = new javax.swing.JLabel();
        cboCCCD2 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblKH_thue = new javax.swing.JTable();
        btnXoaKH = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        lblDongHo3 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblUser2 = new javax.swing.JLabel();
        lblUser3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\BackMini.png")); // NOI18N
        btnBack.setText("Hệ thống");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Quản lý dịch vụ");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tblAnUong.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblAnUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã vât phẩm", "Vật phẩm", "Giá", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAnUong.setGridColor(new java.awt.Color(153, 153, 153));
        tblAnUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnUongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAnUong);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tên vật phẩm :");

        lblTenVP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenVP.setForeground(new java.awt.Color(0, 0, 255));
        lblTenVP.setText("Coca");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Phải trả :");

        lblPhaiTraBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhaiTraBan.setForeground(new java.awt.Color(255, 0, 0));
        lblPhaiTraBan.setText("0");

        btnThanhToanBan.setBackground(new java.awt.Color(255, 255, 255));
        btnThanhToanBan.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnThanhToanBan.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Goimoinini.jpg")); // NOI18N
        btnThanhToanBan.setText("Thanh toán");
        btnThanhToanBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanBanActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Giá vật phẩm :");

        lblGiaVP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaVP.setForeground(new java.awt.Color(0, 0, 255));
        lblGiaVP.setText("15000 VNĐ");

        btnThem.setBackground(new java.awt.Color(204, 204, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Add.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        tblAnUong2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_DV", "Mã VP", "Tên VP", "Giá", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAnUong2);

        btnXoa.setBackground(new java.awt.Color(204, 204, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Delete.png")); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lblUser4.setBackground(new java.awt.Color(0, 204, 255));
        lblUser4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUser4.setForeground(new java.awt.Color(0, 0, 255));
        lblUser4.setText("Mã hoá đơn :");

        lblMaHD.setBackground(new java.awt.Color(0, 204, 255));
        lblMaHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMaHD.setForeground(new java.awt.Color(255, 0, 204));
        lblMaHD.setText("0");

        btnTaoMoi.setBackground(new java.awt.Color(204, 204, 255));
        btnTaoMoi.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTaoMoi.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Refresh-icon.png")); // NOI18N
        btnTaoMoi.setText("Tao Mới");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        lblPhaiTraBan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhaiTraBan1.setForeground(new java.awt.Color(255, 0, 0));
        lblPhaiTraBan1.setText("VNĐ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTenVP, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGiaVP)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(lblUser4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMaHD)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPhaiTraBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPhaiTraBan1)
                                .addGap(131, 131, 131))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThanhToanBan)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnThanhToanBan, btnThem});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblTenVP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblGiaVP)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnTaoMoi)
                            .addComponent(btnThanhToanBan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaHD)
                            .addComponent(lblUser4)
                            .addComponent(jLabel3)
                            .addComponent(lblPhaiTraBan)
                            .addComponent(lblPhaiTraBan1))))
                .addGap(120, 120, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnThanhToanBan, btnThem});

        jTabbedPane1.addTab("Ăn uống", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tblThue.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã vật phẩm", "Vật phẩm", "Giá thuê", "Số lượng"
            }
        ));
        tblThue.setGridColor(new java.awt.Color(153, 153, 153));
        tblThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThueMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblThue);
        if (tblThue.getColumnModel().getColumnCount() > 0) {
            tblThue.getColumnModel().getColumn(2).setHeaderValue("Giá thuê");
            tblThue.getColumnModel().getColumn(3).setHeaderValue("Số lượng");
        }

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Tên vật phẩm :");

        lblTenVPThue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenVPThue.setForeground(new java.awt.Color(0, 0, 255));
        lblTenVPThue.setText("2 mảnh nữ");

        btnThue.setBackground(new java.awt.Color(255, 255, 255));
        btnThue.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnThue.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Goimoinini.jpg")); // NOI18N
        btnThue.setText("Thuê");
        btnThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThueActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Giá thuê :");

        lblGiaVPThue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaVPThue.setForeground(new java.awt.Color(0, 0, 255));
        lblGiaVPThue.setText("200000 VNĐ");

        btnThemThue.setBackground(new java.awt.Color(204, 204, 255));
        btnThemThue.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnThemThue.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Add.png")); // NOI18N
        btnThemThue.setText("Thêm");
        btnThemThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThueActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Họ tên :");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("CCCD :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Phải trả :");

        lblPhaiTraThue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhaiTraThue.setForeground(new java.awt.Color(255, 0, 0));
        lblPhaiTraThue.setText("0");

        btnCFCCCD.setBackground(new java.awt.Color(204, 204, 255));
        btnCFCCCD.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnCFCCCD.setText("Xác nhận CCCD");
        btnCFCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCFCCCDActionPerformed(evt);
            }
        });

        tblThue2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_DV", "Mã MP", "Tên VP", "Giá thuê", "Số lượng"
            }
        ));
        jScrollPane6.setViewportView(tblThue2);

        btnXoaThue.setBackground(new java.awt.Color(204, 204, 255));
        btnXoaThue.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnXoaThue.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Delete.png")); // NOI18N
        btnXoaThue.setText("Xoá");
        btnXoaThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThueActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("CCCD :");

        lblCCCDCF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCCCDCF.setForeground(new java.awt.Color(0, 0, 255));
        lblCCCDCF.setText("Null");

        cboCCCD1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        cboCCCD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboCCCD1MouseClicked(evt);
            }
        });
        cboCCCD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCCCD1ActionPerformed(evt);
            }
        });

        btnTaoMoi_Thue.setBackground(new java.awt.Color(204, 204, 255));
        btnTaoMoi_Thue.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTaoMoi_Thue.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Refresh-icon.png")); // NOI18N
        btnTaoMoi_Thue.setText("Tao Mới");
        btnTaoMoi_Thue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoi_ThueActionPerformed(evt);
            }
        });

        lblUser5.setBackground(new java.awt.Color(0, 204, 255));
        lblUser5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUser5.setForeground(new java.awt.Color(0, 0, 255));
        lblUser5.setText("Mã hoá đơn :");

        lblMaHD_thue.setBackground(new java.awt.Color(0, 204, 255));
        lblMaHD_thue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMaHD_thue.setForeground(new java.awt.Color(255, 0, 204));
        lblMaHD_thue.setText("0");

        lblPhaiTraBan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhaiTraBan2.setForeground(new java.awt.Color(255, 0, 0));
        lblPhaiTraBan2.setText("VNĐ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPhaiTraThue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                        .addComponent(lblPhaiTraBan2)
                                        .addGap(174, 174, 174))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCCCDCF)
                                        .addGap(83, 83, 83)
                                        .addComponent(btnThue, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblGiaVPThue))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(lblUser5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblMaHD_thue)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCFCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblTenVPThue))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(txtHoTenThue, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cboCCCD1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btnThemThue, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnXoaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTaoMoi_Thue, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemThue)
                            .addComponent(btnXoaThue)
                            .addComponent(btnTaoMoi_Thue))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(lblCCCDCF)
                                    .addComponent(jLabel23)
                                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThue)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhaiTraThue)
                                    .addComponent(jLabel5)
                                    .addComponent(lblPhaiTraBan2)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblTenVPThue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(lblGiaVPThue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblUser5)
                                    .addComponent(lblMaHD_thue)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnCFCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoTenThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCCCD1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thuê mượn", jPanel2);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        tblDCT.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_DV", "CCCD", "", "Tên VP", "Giá thuê", "Số lượng"
            }
        ));
        tblDCT.setGridColor(new java.awt.Color(153, 153, 153));
        tblDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDCTMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblDCT);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Phải trả :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("2200000 VNĐ");

        btnTra.setBackground(new java.awt.Color(255, 255, 255));
        btnTra.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTra.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Goimoinini.jpg")); // NOI18N
        btnTra.setText("Trả");
        btnTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Khách hàng :");

        lblTenKh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenKh.setForeground(new java.awt.Color(0, 0, 255));

        cboCCCD2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        cboCCCD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCCCD2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTra, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 637, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(135, 135, 135))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(lblTenKh))
                            .addComponent(cboCCCD2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cboCCCD2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblTenKh))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTra)
                        .addGap(222, 222, 222))))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 952, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Đang cho thuê", jPanel7);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        tblKH_thue.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblKH_thue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CCCD", "Họ tên", "Trạng thái"
            }
        ));
        tblKH_thue.setGridColor(new java.awt.Color(153, 153, 153));
        tblKH_thue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKH_thueMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblKH_thue);

        btnXoaKH.setBackground(new java.awt.Color(204, 204, 255));
        btnXoaKH.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnXoaKH.setIcon(new javax.swing.ImageIcon("D:\\Code\\DUAN1\\QLHOBOI\\img\\Delete.png")); // NOI18N
        btnXoaKH.setText("Xoá");
        btnXoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnXoaKH))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Khách hàng", jPanel9);

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));

        lblDongHo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDongHo3.setForeground(new java.awt.Color(255, 0, 0));
        lblDongHo3.setText("12 : 00 ");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 0, 0));
        lblDate.setText("12/12/2020");

        lblUser2.setBackground(new java.awt.Color(0, 204, 255));
        lblUser2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUser2.setForeground(new java.awt.Color(255, 0, 204));
        lblUser2.setText("Tên Gói Bơi");

        lblUser3.setBackground(new java.awt.Color(0, 204, 255));
        lblUser3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUser3.setForeground(new java.awt.Color(0, 0, 255));
        lblUser3.setText("Nhân viên :");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblDongHo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUser2)
                .addGap(23, 23, 23))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDongHo3)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser2)
                    .addComponent(lblUser3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        try {
            HomeNV ql = new HomeNV();
            ql.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Lỗi ql");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKHActionPerformed
        // TODO add your handling code here:
        try {
            if (tblKH_thue.getSelectedRow() > -1) {
            } else {
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá không ?", "Cảnh báo xoá", JOptionPane.YES_NO_OPTION);
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            } else {
            }
            index = tblKH_thue.getSelectedRow();
            if (tblKH_thue.getValueAt(index, 2).toString().equalsIgnoreCase("Đang thuê")) {
                JOptionPane.showMessageDialog(rootPane, "Khách hàng này đang thuê, không thể xoá");
                return;
            }
            String sql = "delete from kh_thue where cccd = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, tblKH_thue.getValueAt(index, 0).toString());
            st.executeUpdate();
            LoadDataToTableKH();
            loadDataToComboBox();
            loadDataToComboBox2();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnXoaKHActionPerformed

    private void tblKH_thueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKH_thueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKH_thueMouseClicked

    private void cboCCCD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCCCD2ActionPerformed
        // TODO add your handling code here:
        try {
            LoadDataToTableDangThue();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cboCCCD2ActionPerformed

    private void btnTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraActionPerformed
        // TODO add your handling code here:
        try {
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn trả không ?", "", JOptionPane.YES_NO_OPTION);
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            } else {
            }
            index = tblDCT.getSelectedRow();

            String SL = tblDCT.getValueAt(index, 5).toString();
            System.out.println(SL);
            String sql3 = "Update dichvu set soluongvp = soluongvp + " + SL + " where mavp = ?";
            PreparedStatement st3 = k.cn.prepareStatement(sql3);
            st3.setString(1, tblDCT.getValueAt(index, 2).toString());
            st3.executeUpdate();

            String sql = "delete from hoadondvct_thue where cccd = ? and id_thue = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, cboCCCD2.getSelectedItem().toString());
            st.setString(2, tblDCT.getValueAt(index, 0).toString());
            st.executeUpdate();

            lblTenKh.setText("");
            LoadDataToTableDangThue();
            LoadDataToTableThue();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnTraActionPerformed

    private void tblDCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDCTMouseClicked
        // TODO add your handling code here:
        try {
            index = tblDCT.getSelectedRow();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tblDCTMouseClicked

    private void btnTaoMoi_ThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoi_ThueActionPerformed
        // TODO add your handling code here:
        try {
            if (lblCCCDCF.getText().equalsIgnoreCase("null")) {
                JOptionPane.showMessageDialog(null, "Mời bạn nhập căn cước công dân");
                return;
            }
            //điều kiện
            //            System.out.println(tblThue2.getRowCount());
            //            if (tblThue2.getRowCount() != 0) {
            //                JOptionPane.showMessageDialog(null, "Bạn cần làm việc xong với hoá đơn : " + lblMaHD.getText());
            //                return;
            //            } else {
            //            }
            //lấy ra ngày tháng năm
            int ngay, thang, nam;
            String day = lblDate.getText();
            ngay = Integer.parseInt(day.substring(0, 2));
            thang = Integer.parseInt(day.substring(3, 5));
            nam = Integer.parseInt(day.substring(6, 10));
            String datee = thang + "-" + ngay + "-" + nam;

            //thêm bảng hoá đơn mới
            String sql = "insert into hoadondv_thue(maloaidoanhthu,username,thanhtien,thoigian,trangthai,cccd) values(?,?,?,?,?,?)";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, "DoanhThuDichVu");
            st.setString(2, lblUser2.getText());
            st.setInt(3, 0);
            st.setString(4, datee);
            st.setString(5, "Đang được chọn thuê");
            st.setString(6, lblCCCDCF.getText());
            st.executeUpdate();

            //Load lại các bảng
            loadMaHD_Thue();
            JOptionPane.showMessageDialog(rootPane, "Bạn vừa tạo thành công hoá đơn : " + lblMaHD_thue.getText());
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnTaoMoi_ThueActionPerformed

    private void cboCCCD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCCCD1ActionPerformed
        // TODO add your handling code here:
        try {
            index = cboCCCD1.getSelectedIndex();
            //            System.out.println(cboCCCD1.getSelectedIndex());
            lblCCCDCF.setText(cboCCCD1.getItemAt(index));
            txtCCCD.setText(cboCCCD1.getItemAt(index));
            String sql = "select hoten from kh_thue where cccd = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, txtCCCD.getText());
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                txtHoTenThue.setText(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cboCCCD1ActionPerformed

    private void cboCCCD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCCCD1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCCCD1MouseClicked

    private void btnXoaThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThueActionPerformed
        // TODO add your handling code here:
        try {
            if (tblThue2.getSelectedRow() > -1) {
            } else {
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá không ?", "Cảnh báo xoá", JOptionPane.YES_NO_OPTION);
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            } else {
            }
            index = tblThue2.getSelectedRow();
            String SL = tblThue2.getValueAt(index, 4).toString();
            String sql3 = "Update dichvu set soluongvp = soluongvp + " + SL + " where mavp = ?";
            PreparedStatement st3 = k.cn.prepareStatement(sql3);
            st3.setString(1, tblThue2.getValueAt(index, 1).toString());
            st3.executeUpdate();

            String sql = "delete from HOADONDVCT_Thue where id_thue = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, tblThue2.getValueAt(index, 0).toString());
            st.executeUpdate();
            LoadDataToTableThue();
            LoadDataToTableThue2();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnXoaThueActionPerformed

    private void btnCFCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCFCCCDActionPerformed
        try {
            // TODO add your handling code here:
            try {
                Integer.parseInt(txtCCCD.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "CCCD phải là số");
                return;
            }
            //điều kiện txthoten và txt cccd
            if (txtHoTenThue.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Phải điền họ tên người thuê : ");
                txtHoTenThue.requestFocus();
                return;
            }
            if (txtCCCD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Phải điền Căn cước công dân người thuê : ");
                txtCCCD.requestFocus();
                return;
            }
            //check trùng khách hàng thuê
            String sql4 = "select cccd from kh_thue";
            String cccd = txtCCCD.getText();
            PreparedStatement st4 = k.cn.prepareStatement(sql4);
            ResultSet rs2 = st4.executeQuery();
            while (rs2.next()) {
                if (cccd.equalsIgnoreCase(rs2.getString(1))) {
                    JOptionPane.showMessageDialog(rootPane, "CCCD này đang được dùng để thuê");
                    return;
                }
            }
            //Insert Khách hàng thuê mới
            String sql = "insert into KH_Thue values(?,?,?)";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, txtCCCD.getText());
            st.setString(2, txtHoTenThue.getText());
            st.setString(3, "Đang không thuê");
            st.executeUpdate();

            //load lại các bảng
            loadDataToComboBox();
            loadDataToComboBox2();
            LoadDataToTableKH();
            lblCCCDCF.setText(txtCCCD.getText());
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDichVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCFCCCDActionPerformed

    private void btnThemThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThueActionPerformed
        // TODO add your handling code here:
        try {
            //
            if (lblMaHD_thue.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(rootPane, "Bạn cần tạo 1 hoá đơn mới (Tạo mới)");
                return;
            }

            //Điều kiện phải chọn row ở tblThue
            if (tblThue.getSelectedRow() > -1) {
            } else {
                return;
            }
            // Số lượng == null => return
            String SL = JOptionPane.showInputDialog("Mời nhập số lượng");
            if (SL != null) {

            } else {
                return;
            }
            // check number số lượng
            try {
                Integer.parseInt(SL);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Yêu cầu bạn nhập số");
                return;
            }
            // check null số lượng
            if (SL.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Phải nhập số lượng");
                return;
            }
            index = tblThue.getSelectedRow();
            if (Integer.parseInt(SL) > Integer.parseInt(tblThue.getValueAt(index, 3).toString())) {
                JOptionPane.showMessageDialog(rootPane, "Không còn đủ số lượng vật phẩm");
                return;
            }

            //số lượng vật phẩm trừ
            String sql = "Update dichvu set soluongvp = soluongvp - " + SL + " where mavp = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, tblThue.getValueAt(index, 0).toString());
            st.executeUpdate();

            //Insert vật phẩm vào tblThue2 có gán CCCD
            String sql2 = "insert into HOADONDVCT_Thue (MAHOADONDV,mavp,giavp,soluong,cccd) values(?,?,?,?,?)";
            PreparedStatement st2 = k.cn.prepareStatement(sql2);
            st2.setString(1, lblMaHD_thue.getText());
            st2.setString(2, tblThue.getValueAt(index, 0).toString());
            st2.setString(3, tblThue.getValueAt(index, 2).toString());
            st2.setString(4, SL);
            st2.setString(5, lblCCCDCF.getText());
            st2.executeUpdate();

            //Insert vật phẩm vào tblThue2 có gán CCCD
            String sql3 = "insert into LUU_HD_Thue (MAHOADONDV,mavp,giavp,soluong,cccd) values(?,?,?,?,?)";
            PreparedStatement st3 = k.cn.prepareStatement(sql3);
            st3.setString(1, lblMaHD_thue.getText());
            st3.setString(2, tblThue.getValueAt(index, 0).toString());
            st3.setString(3, tblThue.getValueAt(index, 2).toString());
            st3.setString(4, SL);
            st3.setString(5, lblCCCDCF.getText());
            st3.executeUpdate();

            //Load lại Jtable
            LoadDataToTableThue();
            LoadDataToTableThue2();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnThemThueActionPerformed

    private void btnThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThueActionPerformed
        // Button Thuê ở cho thuê
        try {
            //điều kiện
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thanh toán không ?", "Thanh toán", JOptionPane.YES_NO_OPTION);
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            } else {
            }

            //sửa trjang thái của hoá đơn thành ĐAng cho thuê theo CCCD
            String sql3 = "update HOADONDV_thue set TrangThai = N'Đang cho thuê' where cccd = ?";
            PreparedStatement st3 = k.cn.prepareStatement(sql3);
            st3.setString(1, lblCCCDCF.getText());
            st3.executeUpdate();

            String sql2 = "update HOADONDV_thue set thanhtien = ? where cccd = ?";
            PreparedStatement st2 = k.cn.prepareStatement(sql2);
            st2.setString(1, lblPhaiTraThue.getText());
            st2.setString(2, lblCCCDCF.getText());
            st2.executeUpdate();

            //sửa trjang thái của hoá đơn thành ĐAng cho thuê theo CCCD
            String sql = "update kh_thue set TrangThaiKH = N'Đang thuê' where cccd = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, lblCCCDCF.getText());
            st.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Bạn phải thanh toán : " + lblPhaiTraThue.getText());

            LoadDataToTableKH();
            LoadDataToTableThue2();
            loadDataToComboBox2();
            LoadDataToTableDangThue();
            txtCCCD.setText("");
            txtHoTenThue.setText("");
            lblMaHD_thue.setText("0");
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnThueActionPerformed

    private void tblThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThueMouseClicked
        // TODO add your handling code here:
        try {
            index = tblThue.getSelectedRow();
            showDetailThue(index);
        } catch (Exception e) {
            System.out.println("Lỗi click");
        }
    }//GEN-LAST:event_tblThueMouseClicked

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        // TODO add your handling code here:
        try {
            if (tblAnUong2.getRowCount() != 0) {
                JOptionPane.showMessageDialog(null, "Bạn cần làm việc xong với hoá đơn : " + lblMaHD.getText());
                return;
            } else {
            }
            int ngay, thang, nam;
            String day = lblDate.getText();
            ngay = Integer.parseInt(day.substring(0, 2));
            thang = Integer.parseInt(day.substring(3, 5));
            nam = Integer.parseInt(day.substring(6, 10));
            String datee = thang + "-" + ngay + "-" + nam;

            String sql = "insert into hoadondv_Mua(maloaidoanhthu,username,thanhtien,thoigian,trangthai) values(?,?,?,?,?)";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, "DoanhThuDichVu");
            st.setString(2, lblUser2.getText());
            st.setInt(3, 0);
            st.setString(4, datee);
            st.setString(5, "Đang được chọn");
            st.executeUpdate();
            loadMaHD();
            JOptionPane.showMessageDialog(rootPane, "Bạn vừa tạo thành công hoá đơn : " + lblMaHD.getText());
        } catch (HeadlessException | NumberFormatException | SQLException e) {
        }
    }//GEN-LAST:event_btnTaoMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            if (tblAnUong2.getSelectedRow() > -1) {
            } else {
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá không ?", "Cảnh báo xoá", JOptionPane.YES_NO_OPTION);
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            } else {
            }
            index = tblAnUong2.getSelectedRow();

            String SL = tblAnUong2.getValueAt(index, 4).toString();
            String sql3 = "Update dichvu set soluongvp = soluongvp + " + SL + " where mavp = ?";
            PreparedStatement st3 = k.cn.prepareStatement(sql3);
            st3.setString(1, tblAnUong2.getValueAt(index, 1).toString());
            st3.executeUpdate();

            String sql2 = "delete from hoadondvct_mua where mahoadondv = ?";
            PreparedStatement st2 = k.cn.prepareStatement(sql2);
            st2.setString(1, lblMaHD.getText());
            st2.executeUpdate();
            LoadDataToTableBan();
            LoadDataToTableBan2();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {

            if (lblMaHD.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(rootPane, "Bạn cần tạo 1 hoá đơn mới (Tạo mới)");
                return;
            }
            if (tblAnUong.getSelectedRow() > -1) {
            } else {
                return;
            }
            String SL = JOptionPane.showInputDialog(rootPane, "Mời nhập số lượng");
            if (SL != null) {

            } else {
                return;
            }
            if (SL.isEmpty() || SL.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Phải nhập số lượng");
                return;
            }
            try {
                Integer.parseInt(SL);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Yêu cầu bạn nhập số");
                return;
            }
            index = tblAnUong.getSelectedRow();
            if (Integer.parseInt(SL) > Integer.parseInt(tblAnUong.getValueAt(index, 3).toString())) {
                JOptionPane.showMessageDialog(rootPane, "Không còn đủ số lượng vật phẩm");
                return;
            }

            // Thêm vật phẩm mua vào hoá đơn chi tiết
            String sql = "insert into HOADONDVCT_Mua (MAHOADONDV,mavp,soluong,giavp) values(?,?,?,?)";
            PreparedStatement st = k.cn.prepareStatement(sql);
            int id = Integer.parseInt(lblMaHD.getText());
            st.setInt(1, id);
            st.setString(2, tblAnUong.getValueAt(index, 0).toString());
            st.setInt(3, Integer.parseInt(SL));
            st.setInt(4, Integer.parseInt(tblAnUong.getValueAt(index, 2).toString()));
            st.executeUpdate();

            //số lượng vật phẩm trừ
            String sql3 = "Update dichvu set soluongvp = soluongvp - " + SL + " where mavp = ?";
            PreparedStatement st3 = k.cn.prepareStatement(sql3);
            st3.setString(1, tblAnUong.getValueAt(index, 0).toString());
            st3.executeUpdate();

            //Load lại Jtable
            LoadDataToTableBan();
            LoadDataToTableBan2();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThanhToanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanBanActionPerformed
        // TODO add your handling code here:
        try {
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thanh toán không ?", "Thanh toán", JOptionPane.YES_NO_OPTION);
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            } else {
            }

            String sql2 = "update hoadondv_Mua set trangthai = N'Đã bán' where mahoadondv = ?";
            PreparedStatement st2 = k.cn.prepareStatement(sql2);
            st2.setString(1, lblMaHD.getText());
            st2.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Bạn phải thanh toán : " + lblPhaiTraBan.getText());

            //tổng bằng tổng hoá đơn
            //            int tong = 0;
            //            int size = tblAnUong2.getRowCount();
            //            for (int i = 0; i < size; i++) {
            //                tong = tong + Integer.parseInt(tblAnUong2.getValueAt(i, 3).toString()) * Integer.parseInt(tblAnUong2.getValueAt(i, 4).toString());
            //            }
            String sql = "update hoadondv_Mua set thanhtien = ? where mahoadondv = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, lblPhaiTraBan.getText());
            st.setString(2, lblMaHD.getText());

            st.executeUpdate();

            lblMaHD.setText("0");
            LoadDataToTableBan2();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnThanhToanBanActionPerformed

    private void tblAnUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnUongMouseClicked
        // TODO add your handling code here:
        try {
            index = tblAnUong.getSelectedRow();
            showDetailBan(index);
        } catch (Exception e) {
            System.out.println("Lỗi click");
        }
    }//GEN-LAST:event_tblAnUongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDichVu().setVisible(true);
            }
        });
    }

    private void LoadUser() {
        try {
            String sql = "select * from tkol";
            Statement st = k.cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                lblUser2.setText(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void LoadDataToTableKH() {
        try {
            model = (DefaultTableModel) tblKH_thue.getModel();
            model.setRowCount(0);
            String sql = "select * from kh_thue";
            PreparedStatement st = k.cn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                model.addRow(row);
            }

        } catch (SQLException e) {
            System.out.println("Lỗi tải dữ liệu");
        }
    }

    private void LoadDataToTableBan() {
        try {
            model = (DefaultTableModel) tblAnUong.getModel();
            model.setRowCount(0);
            String sql = "select mavp,tenvp,giavp,soluongvp from DICHVU where MALDV = 'dvb'";
            PreparedStatement st = k.cn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getString(4));
                model.addRow(row);
            }

        } catch (SQLException e) {
            System.out.println("Lỗi tải dữ liệu");
        }
    }

    private void LoadDataToTableBan2() {
        try {

            model = (DefaultTableModel) tblAnUong2.getModel();
            model.setRowCount(0);
            String sql = "SELECT ID_Mua,HOADONDVCT_Mua.mavp, tenvp,HOADONDVCT_Mua.giavp,"
                    + " SOLUONG from HOADONDVCT_Mua join DICHVU on DICHVU.MAVP ="
                    + " HOADONDVCT_Mua.Mavp where mahoadondv = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, lblMaHD.getText());
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getInt(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getString(4));
                row.add(rs.getString(5));
                model.addRow(row);
            }
            int tong = 0;
            int size = tblAnUong2.getRowCount();
            for (int i = 0; i < size; i++) {
                tong = tong + Integer.parseInt(tblAnUong2.getValueAt(i, 3).toString()) * Integer.parseInt(tblAnUong2.getValueAt(i, 4).toString());
            }
            lblPhaiTraBan.setText(String.valueOf(tong));

        } catch (SQLException e) {
            System.out.println("Lỗi tải dữ liệu bảng ăn uống 2 \n" + e);
        }
    }

    private void LoadDataToTableThue() {
        try {
            model = (DefaultTableModel) tblThue.getModel();
            model.setRowCount(0);
            String sql = "select mavp,tenvp,giavp,soluongvp from DICHVU where MALDV = 'dvt'";
            PreparedStatement st = k.cn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getString(4));
                model.addRow(row);
            }

        } catch (SQLException e) {
            System.out.println("Lỗi tải dữ liệu");
        }
    }

    private void LoadDataToTableThue2() {
        try {
            model = (DefaultTableModel) tblThue2.getModel();
            model.setRowCount(0);
            String sql = "select id_thue, t.mavp,tenvp, t.giavp,soluong from HOADONDVCT_Thue t \n"
                    + "join DICHVU d on d.MAVP = t.MAVP\n"
                    + "join HOADONDV_Thue h on t.MAHOADONDV = h.MAHOADONDV\n"
                    + "where trangthai = N'đang được chọn thuê'";
            PreparedStatement st = k.cn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getInt(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getInt(4));
                row.add(rs.getInt(5));
                model.addRow(row);
            }
            int tong = 0;
            int size = tblThue2.getRowCount();
            for (int i = 0; i < size; i++) {
                tong = tong + Integer.parseInt(tblThue2.getValueAt(i, 3).toString()) * Integer.parseInt(tblThue2.getValueAt(i, 4).toString());
            }
            lblPhaiTraThue.setText(String.valueOf(tong));

        } catch (SQLException e) {
            System.out.println("Lỗi tải dữ liệu \n" + e);
        }
    }

    private void LoadDataToTableDangThue() {
        try {
            if (cboCCCD2.getItemCount() == 0) {
                return;
            }
            String sqll = "select COUNT(*) from HOADONDV_Thue where TrangThai = N'Đang cho thuê'";
            Statement st2 = k.cn.createStatement();
            ResultSet rs2 = st2.executeQuery(sqll);
            while (rs2.next()) {
                int count = Integer.parseInt(rs2.getString(1));
                if (count == 0) {
                    return;
                }
            }
            model = (DefaultTableModel) tblDCT.getModel();
            model.setRowCount(0);
            String sql = "select id_thue, t.CCCD,d.mavp,tenvp, t.giavp,soluong,hoten from HOADONDVCT_Thue t \n"
                    + "join DICHVU d on d.MAVP = t.MAVP\n"
                    + "join HOADONDV_Thue h on t.MAHOADONDV = h.MAHOADONDV\n"
                    + "join KH_Thue kh on kh.CCCD = h.CCCD\n"
                    + "where trangthai = N'đang cho thuê' and t.CCCD = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, cboCCCD2.getSelectedItem().toString());
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getInt(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getString(4));
                row.add(rs.getInt(5));
                row.add(rs.getInt(6));
                model.addRow(row);
                lblTenKh.setText(rs.getString(7));
            }

        } catch (SQLException e) {
            System.out.println("Lỗi tải dữ liệu \n" + e);
        }
    }

    private void showDetailBan(int index) {
        lblTenVP.setText(tblAnUong.getValueAt(index, 1).toString());
        lblGiaVP.setText(tblAnUong.getValueAt(index, 2).toString());
        tblAnUong.setRowSelectionInterval(index, index);
    }

    private void showDetailThue(int index) {
        lblTenVPThue.setText(tblThue.getValueAt(index, 1).toString());
        lblGiaVPThue.setText(tblThue.getValueAt(index, 2).toString());
        tblThue.setRowSelectionInterval(index, index);
    }

    private void loadDataToComboBox() {
        try {
            cboCCCD1.removeAllItems();
            String sql = "Select cccd from kh_thue";
            Statement st = k.cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                cboCCCD1.addItem(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println(e + "cb1");
        }
    }

    private void loadDataToComboBox2() {
        try {
            cboCCCD2.removeAllItems();
            String sql = "Select cccd from kh_thue where trangthaikh = N'đang thuê'";
            Statement st = k.cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                cboCCCD2.addItem(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void dongHo() {
        Thread t = new Thread() {
            String text;
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss aa");

            @Override
            public void run() {
                while (true) {
                    Date d = new Date(); //Tạo đối tượng Date để lấy giờ hệ thống
                    text = sdf.format(d);
                    lblDongHo3.setText(text);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        break;
                    }
                }
            }
        };
        t.start();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String dateFormat = formatter.format(date);
        lblDate.setText(dateFormat);
    }

    private void loadMaHD() {
        try {
            String sql = "select TOP(1) mahoadondv from hoadondv_Mua order by mahoadondv DESC";
            Statement st = k.cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                lblMaHD.setText(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void loadMaHD_Thue() {
        try {
            String sql = "select TOP(1) mahoadondv from hoadondv_thue order by mahoadondv DESC";
            Statement st = k.cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                lblMaHD_thue.setText(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCFCCCD;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnTaoMoi_Thue;
    private javax.swing.JButton btnThanhToanBan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemThue;
    private javax.swing.JButton btnThue;
    private javax.swing.JButton btnTra;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaKH;
    private javax.swing.JButton btnXoaThue;
    private javax.swing.JComboBox<String> cboCCCD1;
    private javax.swing.JComboBox<String> cboCCCD2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCCCDCF;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDongHo3;
    private javax.swing.JLabel lblGiaVP;
    private javax.swing.JLabel lblGiaVPThue;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblMaHD_thue;
    private javax.swing.JLabel lblPhaiTraBan;
    private javax.swing.JLabel lblPhaiTraBan1;
    private javax.swing.JLabel lblPhaiTraBan2;
    private javax.swing.JLabel lblPhaiTraThue;
    private javax.swing.JLabel lblTenKh;
    private javax.swing.JLabel lblTenVP;
    private javax.swing.JLabel lblTenVPThue;
    private javax.swing.JLabel lblUser2;
    private javax.swing.JLabel lblUser3;
    private javax.swing.JLabel lblUser4;
    private javax.swing.JLabel lblUser5;
    private javax.swing.JTable tblAnUong;
    private javax.swing.JTable tblAnUong2;
    private javax.swing.JTable tblDCT;
    private javax.swing.JTable tblKH_thue;
    private javax.swing.JTable tblThue;
    public javax.swing.JTable tblThue2;
    public javax.swing.JTextField txtCCCD;
    public javax.swing.JTextField txtHoTenThue;
    // End of variables declaration//GEN-END:variables
}
